jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v5
    - uses: hecrj/setup-rust-action@v2
    - uses: actions/download-artifact@v6
      with:
        name: dist
        path: dist
    - run: sudo apt-get update && sudo apt-get install chromium-browser
    - run: |
        curl -LO https://github.com/svenstaro/miniserve/releases/download/v0.6.0/miniserve-linux-x86_64
        chmod a+x miniserve-linux-x86_64
        sudo mv miniserve-linux-x86_64 /usr/local/bin/miniserve
    - run: cargo test

  fmt:
    name: cargo fmt --check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: hecrj/setup-rust-action@v2
      with: { components: rustfmt }
    - run: cargo fmt -- --check

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: hecrj/setup-rust-action@v2
      with: { components: clippy }
    - run: cargo clippy --workspace --all-targets --locked -- -D warnings

on:
  merge_group:
    types: [checks_requested]
  pull_request:
    branches: [master]
